### ISSUE TITLE
Need it to work with random size jigsaw pieces

### ISSUE THREAD

**Issue by frajos100** [nemanja-m/gaps#10]
Need it to work with random size jigsaw pieces. When the image is broken down into square based jigsaw pieces it works wonderfully.  Was wondering how to change the code to break an image into random jigsaw puzzle and how to run the code to automatically solve the jigsaw pieces.

**Comment by nemanja-m** [comment]
Do you mean random rectangular shape or any shape?

**Comment by frajos100** [comment]
I am referring to the jigsaw puzzle pieces of different shapes that can fit into each other which is easier to solve than the rectangular jigsaw pieces.
