### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by jorlogicus** [nemanja-m/gaps#12]
Hello @nemanja-m, today while exploring GitHub looking for interesting projects found yours and I would love to contribute by designing a logo for it. I'm a designer in development and an open source enthusiast. We would be working together to create the design that fits best. Of course it's totally free and you can quit whenever you want. In case you agree, please let me know any preferences you may have about colors, shapes, etc you may have.  

Kind regards.

**Comment by nemanja-m** [comment]
Hi @jorlogicus, feel free to experiment with logo in any way you want. You can maybe create several prototypes for a logo and then we can pick one. Thanks!

**Comment by jorlogicus** [comment]
Sorry, It's been crazy days lately. Here I present you some designs to start with, let me know your thoughts. 
![recurso_2](https://user-images.githubusercontent.com/46901656/52536428-c4815080-2d30-11e9-8422-b5c9d3bc82f0.png)

**Comment by nemanja-m** [comment]
I was busy too. I like the 1st logo, it looks really nice.

**Comment by jorlogicus** [comment]
You mean this one?
![image](https://user-images.githubusercontent.com/46901656/53292286-717ab500-3796-11e9-9261-121fe7f15fcf.png)
If yes, anything you want to add/modify? 
After you finally select the design you like most, I will prepare the proper files and upload them through a pull request if you agree with that.

**Comment by nemanja-m** [comment]
Yes, that's the logo but I would like to change the typeface for letter G because it looks like one from Google's logo. Except for typeface, everything is looking good to me. When you finish, just open PR.

**Comment by jorlogicus** [comment]
Hello again, here I present you some proposals

![](https://cdn.discordapp.com/attachments/451449919648169984/550853448967520257/Recurso_5.png)

**Comment by nemanja-m** [comment]
I like the first logo in 2nd row. You can add that logo, update README and make PR when you are ready. Thank you!

**Comment by jorlogicus** [comment]
Pull request has been created (#13). Also uploaded all editable files on [Google Drive](https://drive.google.com/open?id=1pAU1Sfj9HpBL8HnUGx9gufxhA__-oZl1 "Google Drive's folder") so please check that link. 

It's been a real pleasure to work with you on this logo for your project, keep up the good work!

I will let you be the one who close this issue, best regards.

**Comment by nemanja-m** [comment]
Thanks!
