### ISSUE TITLE
requirements 模块版本问题

### ISSUE THREAD

**Issue by 189169** [nemanja-m/gaps#34]
└─# pip install -r requirements.txt
Collecting numpy==1.22.0
  Using cached numpy-1.22.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
ERROR: Could not find a version that satisfies the requirement opencv-python==4.2.0.32 (from versions: 3.4.0.14, 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.15.55, 3.4.16.57, 3.4.16.59, 3.4.17.61, 3.4.17.63, 3.4.18.65, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62, 4.5.5.64, 4.6.0.66)
ERROR: No matching distribution found for opencv-python==4.2.0.32

**Comment by nemanja-m** [comment]
It seems that opencv==4.2.0.32 is not supported for Python 3.10. You can try to install another version manually (e.g. `4.3.0.38`).

I'll update the `requirements.txt`.
