### ISSUE TITLE
the opencv-python version??

### ISSUE THREAD

**Issue by kisspanda** [nemanja-m/gaps#36]
when i want to install gaps................

Installed /usr/local/lib/python3.10/dist-packages/gaps-1.0-py3.10.egg
Processing dependencies for gaps==1.0
Searching for opencv-python
Reading https://pypi.org/simple/opencv-python/
error: The read operation timed out

I have installed this
opencv_python-4.5.4.60-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64
from https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/opencv-python/

numpy==1.21.5
opencv-python==4.5.4.60
matplotlib==3.5.1
pytest==6.2.5
pillow==9.0.1
python version is 3.10.4

kali-linux 2022.2

tks

**Comment by nemanja-m** [comment]
Currently, Python 3.10 is not supported.
