### ISSUE TITLE
i installed gaps ,but gaps is used without any reaction,create_puzzle just cant find.

### ISSUE THREAD

**Issue by Dark1es** [nemanja-m/gaps#40]
![image](https://github.com/nemanja-m/gaps/assets/82279926/fd98b076-c0b4-4b37-b60b-afcfc268cbe4)

**Comment by Dark1es** [comment]
i setup in other virtual machine has same problem
![image](https://github.com/nemanja-m/gaps/assets/82279926/d7910baf-d18c-4113-b65a-ccb8d6ed8455)

**Comment by nemanja-m** [comment]
@Dark1es Can you try with the latest version from `main` again? I refactored `gaps` to use Poetry.

Note that CLI is slightly different than before.
